# Generated by Django 3.1.13 on 2021-09-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('contact', models.IntegerField(unique=True)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
